import { createContext, useContext, useState, ReactNode } from "react";

type Lang = "en" | "hi";

interface LanguageContextType {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: (key: string) => string;
}

const translations: Record<Lang, Record<string, string>> = {
  en: {
    // Navbar
    "nav.login": "Log in",
    "nav.start": "Start Free",
    // Coming Soon
    "comingSoon.title": "Registration Coming Soon!",
    "comingSoon.subtitle": "We're working hard to bring you the best learning experience. We'll be launching very soon!",
    "comingSoon.button": "Got it!",

    // Hero
    "hero.badge": "🚀 New: AI-Powered Doubt Solving in Hindi",
    "hero.h1a": "Learning, finally",
    "hero.h1b": "tailored to you.",
    "hero.sub": "Generic courses don't work. LernexAI builds a dynamic curriculum based on your goals, and stays with you as a 24/7 tutor until you master it.",
    "hero.cta": "Start Your Journey — Free",
    "hero.demo": "View Demo",
    "hero.social": "Start your AI-powered learning journey today.",

    // Problem
    "problem.heading": "Why traditional learning is broken.",
    "problem.card1.title": "Fixed Roadmaps",
    "problem.card1.desc": "Most courses follow a \"one-size-fits-all\" path. If you get stuck or need more time on a topic, you're on your own.",
    "problem.card2.title": "Passive Watching",
    "problem.card2.desc": "Watching videos without practice leads to the \"illusion of competence.\" You think you know it until you try to build it.",
    "problem.card3.title": "The LernexAI Approach",
    "problem.card3.desc": "We don't just give you content. We build a personalized ecosystem that adapts as you grow. No more gaps, no more confusion.",
    "problem.badge1": "Dynamic Pace Adjustment",
    "problem.badge2": "Instant Feedback Loops",

    // Features
    "features.heading": "Built for clarity.",
    "features.sub": "Tools designed to help you focus on what matters: actually learning.",
    "features.f1.title": "AI Course Architect",
    "features.f1.desc": "Tell us your goal — be it Web Dev or Stock Market — and our AI will curate a path from the world's best resources, perfectly sequenced for your current level.",
    "features.f2.title": "Bilingual Tutor",
    "features.f2.desc": "Stuck on a concept? Chat with our AI in English or Hindi for simple, conversational explanations that make sense.",
    "features.f3.title": "Micro-Quizzes",
    "features.f3.desc": "Test your knowledge after every module. If you fail, the AI re-explains the topic instantly using a different approach.",
    "features.f4.title": "Industry Recognized",
    "features.f4.desc": "Complete the AI-generated final projects to earn a certificate that proves your practical skills to employers.",

    // HowItWorks
    "how.heading": "Three steps to your first skill.",
    "how.s1.title": "Describe Your Goal",
    "how.s1.desc": "Simply tell us what you want to learn and your current level. E.g., 'I want to build a portfolio website from scratch, I know basic HTML.'",
    "how.s2.title": "Review Roadmap",
    "how.s2.desc": "AI builds a sequence of videos, articles, and projects perfectly sized for you. Tweak it if you want, or just dive in.",
    "how.s3.title": "Learn with Guidance",
    "how.s3.desc": "Start learning. Our AI Tutor is always there in the sidebar to help explain concepts, check code, or test your knowledge.",

    // CTA
    "cta.heading": "Ready to master a new skill?",
    "cta.sub": "Join students who are learning 2x faster with AI-powered personalization. The smartest way to study is finally here.",
    "cta.btn": "Get Started Free",

    // Footer
    "footer.privacy": "Privacy",
    "footer.terms": "Terms",
    "footer.contact": "Contact",
    "footer.aboutFounder": "About Founder",
    "footer.copy": "All rights reserved.",

    // Stats
    "stats.v1": "10K+",  "stats.l1": "Active Students",
    "stats.v2": "200+",  "stats.l2": "Curated Courses",
    "stats.v3": "4.9★",  "stats.l3": "Average Rating",
    "stats.v4": "94%",   "stats.l4": "Completion Rate",

    // Subjects
    "subj.eyebrow": "What You Can Learn",
    "subj.heading": "Any subject. Any level.",
    "subj.sub": "From competitive exams to cutting-edge tech — LernexAI builds a path for every goal.",
    "subj.web": "Web Development", "subj.web.d": "HTML, CSS, React, Node.js and beyond.",
    "subj.stock": "Stock Market",  "subj.stock.d": "Fundamentals, technicals & options trading.",
    "subj.design": "UI/UX Design", "subj.design.d": "Figma, design systems & product thinking.",
    "subj.data": "Data Science",   "subj.data.d": "Python, SQL, pandas, ML pipelines.",
    "subj.ai": "AI & ML",          "subj.ai.d": "Deep learning, LLMs & model deployment.",
    "subj.exam": "Exam Prep",      "subj.exam.d": "JEE, NEET, UPSC, CAT & more.",
    "subj.finance": "Personal Finance","subj.finance.d": "Budgeting, investing & financial planning.",
    "subj.cyber": "Cybersecurity", "subj.cyber.d": "Ethical hacking, networking & security.",

    // Testimonials
    "test.eyebrow": "Student Stories",
    "test.heading": "Real results from real students.",
    "test.featured": "I went from zero coding knowledge to landing my first freelance project in 3 months. The Hindi explanations from the AI tutor were a game-changer — no more Googling basic concepts.",
    "test.featured.name": "Vikram Sharma", "test.featured.role": "Freelance Developer, Jaipur",
    "test.n1": "Arjun Mehta",   "test.r1": "B.Tech Student, Delhi",       "test.q1": "The AI adapts so well. When I struggled with recursion, it tried 3 different explanations until I finally got it. No YouTube video ever did that.",
    "test.n2": "Priya Nair",    "test.r2": "MBA Aspirant, Kochi",          "test.q2": "I was preparing for CAT alongside a job. LernexAI built me a 2-hour daily plan that actually worked. I scored 98 percentile.",
    "test.n3": "Rahul Gupta",   "test.r3": "Stock Trader, Pune",           "test.q3": "Pehle sirf YouTube dekh ke confuse ho jaata tha. LernexAI ne ek proper roadmap diya with quizzes — ab main confidently trade karta hoon.",
    "test.n4": "Sneha Reddy",   "test.r4": "UX Designer, Hyderabad",       "test.q4": "The bento-style project assignments were the best part. Real briefs, real feedback from the AI. My portfolio went from 0 to 6 case studies.",
    "test.n5": "Karan Verma",   "test.r5": "Data Analyst, Bangalore",      "test.q5": "I cleared my SQL interview after just 3 weeks of focused practice. The micro-quizzes kept me honest — no way to skip the hard parts.",
    "test.n6": "Meera Iyer",    "test.r6": "Class 12 Student, Chennai",    "test.q6": "JEE prep felt impossible until LernexAI broke it into tiny daily goals. My parents noticed the change. I stopped panicking at mock tests.",

    // Pricing
    "price.eyebrow": "Pricing",
    "price.heading": "Simple, honest pricing.",
    "price.sub": "Start for free. Upgrade when you're ready to go deeper.",
    "price.month": "month",
    "price.popular": "Most Popular",
    "price.note": "No credit card required to start. Cancel Pro anytime.",
    "price.free.label": "Free",
    "price.free.desc": "Perfect to explore and get started with AI-guided learning.",
    "price.free.f1": "3 AI-generated learning roadmaps",
    "price.free.f2": "Basic bilingual tutor (EN + HI)",
    "price.free.f3": "10 micro-quizzes per month",
    "price.free.f4": "Community forum access",
    "price.free.cta": "Get Started Free",
    "price.pro.label": "Pro",
    "price.pro.desc": "Everything you need to go from beginner to job-ready, fast.",
    "price.pro.f1": "Unlimited AI roadmaps & course curation",
    "price.pro.f2": "24/7 bilingual AI tutor (EN + HI)",
    "price.pro.f3": "Unlimited micro-quizzes & assessments",
    "price.pro.f4": "AI-generated final projects",
    "price.pro.f5": "Industry-recognized certificate",
    "price.pro.f6": "Priority support",
    "price.pro.cta": "Start Pro — ₹499/mo",

    // Certificate
    "cert.eyebrow": "Certification",
    "cert.heading": "Earn a certificate. Prove your skills.",
    "cert.sub": "Finish your AI-curated course, take the final test, and get a graded certificate for just ₹99. The grade you earn reflects exactly how well you mastered the subject.",
    "cert.s1.title": "Complete Your AI Course",
    "cert.s1.desc": "Work through your personalized learning path — videos, projects, and quizzes — until you're ready.",
    "cert.s2.title": "Take the Final Test",
    "cert.s2.desc": "LernexAI gives you a comprehensive exam tailored to your course. Your score determines your certificate grade.",
    "cert.s3.title": "Get Your Graded Certificate",
    "cert.s3.desc": "Pay ₹99, download your certificate with your earned grade, and share it on LinkedIn or with employers.",
    "cert.price.label": "One-time certificate fee",
    "cert.price.note": "Only after you complete the course & test",
    "cert.price.cta": "Learn More",
    "cert.grade.title": "Grade Scale — Your Score, Your Grade",
    "cert.grade.note": "Grades are awarded based on your final test score. Retakes available at no extra cost.",

    // FAQ
    "faq.eyebrow": "FAQ",
    "faq.heading": "Got questions?",
    "faq.q1": "Do I need any prior knowledge to start?",
    "faq.a1": "Not at all. LernexAI asks about your current level before building your roadmap. Whether you're a complete beginner or looking to level up, the AI tailors everything accordingly.",
    "faq.q2": "How is this different from Udemy or YouTube?",
    "faq.a2": "Udemy gives you a fixed course. YouTube gives you chaos. LernexAI builds a custom, adaptive path using the best resources from across the web — and stays with you as a live tutor, not a pre-recorded video.",
    "faq.q3": "Can I learn in Hindi?",
    "faq.a3": "Yes! Our AI tutor can explain any concept in Hindi. You can also switch the entire interface to Hindi anytime using the EN|HI toggle in the navbar.",
    "faq.q4": "How does the certificate work?",
    "faq.a4": "After completing your AI-generated final project, our system evaluates your submission and issues a certificate of mastery. It includes the project, your score, and a verifiable link you can share on LinkedIn.",
    "faq.q5": "Is the Pro plan worth it for exam prep (JEE/NEET/UPSC)?",
    "faq.a5": "Absolutely. Pro unlocks unlimited practice tests, detailed performance analytics, and an AI tutor that explains why you got something wrong — not just what the right answer is. Students on Pro consistently outperform on mock tests.",
    "faq.q6": "Can I cancel my Pro subscription anytime?",
    "faq.a6": "Yes, no questions asked. Cancel from your account settings and you'll keep Pro access until the end of the billing period.",

    // Privacy Page
    "privacy.title": "Privacy Policy",
    "privacy.subtitle": "Your data security is our priority",
    "privacy.hero.title": "We Take Your Privacy Seriously",
    "privacy.hero.desc": "At LernexAI, we believe in transparency. This policy explains how we collect, use, and protect your personal information. Your trust matters to us.",
    "privacy.collect.title": "Information We Collect",
    "privacy.collect.desc": "We collect information you provide directly to us when you use our services:",
    "privacy.collect.1": "Name and email address",
    "privacy.collect.2": "Learning preferences and goals",
    "privacy.collect.3": "Usage data and learning progress",
    "privacy.collect.4": "Payment information (securely processed)",
    "privacy.use.title": "How We Use Your Information",
    "privacy.use.1.title": "Personalize Your Learning",
    "privacy.use.1.desc": "Customize curriculum based on your goals and progress",
    "privacy.use.2.title": "Process Payments",
    "privacy.use.2.desc": "Handle subscriptions securely and efficiently",
    "privacy.use.3.title": "Send Updates",
    "privacy.use.3.desc": "Provide educational content and platform updates",
    "privacy.use.4.title": "Improve Our AI",
    "privacy.use.4.desc": "Analyze usage patterns to enhance learning algorithms",
    "privacy.security.title": "Data Security",
    "privacy.security.desc": "We implement industry-standard security measures to protect your personal data:",
    "privacy.security.1": "256-bit encryption for data in transit and at rest",
    "privacy.security.2": "Regular security audits and penetration testing",
    "privacy.security.3": "Strict access controls and authentication",
    "privacy.security.4": "Compliance with data protection regulations",
    "privacy.contact.title": "Questions About Your Privacy?",
    "privacy.contact.desc": "We're here to help. Reach out to us anytime.",

    // Terms Page
    "terms.title": "Terms of Service",
    "terms.subtitle": "Rules and guidelines for using LernexAI",
    "terms.hero.title": "Agreement to Terms",
    "terms.hero.desc": "By using LernexAI, you agree to these terms. Please read them carefully to understand your rights and responsibilities.",
    "terms.accept.title": "Acceptance of Terms",
    "terms.accept.desc": "By accessing or using LernexAI services, you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use our services. These terms constitute a legally binding agreement between you and LernexAI.",
    "terms.responsibilities.title": "User Responsibilities",
    "terms.responsibilities.1": "Maintain account confidentiality",
    "terms.responsibilities.2": "Provide accurate information",
    "terms.responsibilities.3": "Use for educational purposes only",
    "terms.responsibilities.4": "Don't share account credentials",
    "terms.responsibilities.5": "Comply with applicable laws",
    "terms.responsibilities.6": "Report issues promptly",
    "terms.payment.title": "Subscription & Payment",
    "terms.payment.1.title": "Free & Paid Plans",
    "terms.payment.1.desc": "We offer both free and paid subscription plans to suit different needs",
    "terms.payment.2.title": "Recurring Billing",
    "terms.payment.2.desc": "Paid subscriptions are billed on a recurring basis (monthly)",
    "terms.payment.3.title": "Cancellation Policy",
    "terms.payment.3.desc": "Cancel anytime from account settings. Access until billing period ends",
    "terms.payment.4.title": "No Refunds",
    "terms.payment.4.desc": "All fees are non-refundable except as required by law",
    "terms.ip.title": "Intellectual Property",
    "terms.ip.desc": "All content, features, and functionality of LernexAI are owned by LernexAI and are protected by international copyright, trademark, and other intellectual property laws.",
    "terms.ip.note": "Users may not reproduce, distribute, or create derivative works without explicit permission.",
    "terms.liability.title": "Limitation of Liability",
    "terms.liability.desc": "LernexAI shall not be liable for any indirect, incidental, special, or consequential damages arising from the use or inability to use our services. Our liability is limited to the maximum extent permitted by applicable law.",
    "terms.contact.title": "Questions About These Terms?",
    "terms.contact.desc": "We're happy to clarify any doubts you may have.",

    // Contact Page
    "contact.title": "Contact Us",
    "contact.subtitle": "We'd love to hear from you",
    "contact.hero.title": "Get in Touch",
    "contact.hero.desc": "Have questions, feedback, or want to collaborate? We're here to help and would love to hear from you.",
    "contact.email.title": "Email Us",
    "contact.email.desc": "For any inquiries, support, or feedback, please reach out to us via email:",
    "contact.response.title": "Response Time",
    "contact.response.desc": "We typically respond to all emails within 24-48 hours.",
    "contact.response.note": "For urgent matters, please include \"URGENT\" in your subject line.",
    "contact.help.title": "What We Can Help With",
    "contact.help.1.title": "General Inquiries",
    "contact.help.1.desc": "Questions about LernexAI services",
    "contact.help.2.title": "Technical Support",
    "contact.help.2.desc": "Troubleshooting and assistance",
    "contact.help.3.title": "Billing Questions",
    "contact.help.3.desc": "Subscriptions and payments",
    "contact.help.4.title": "Partnerships",
    "contact.help.4.desc": "Collaboration opportunities",
    "contact.help.5.title": "Feedback",
    "contact.help.5.desc": "Suggestions and improvements",
    "contact.help.6.title": "Press & Media",
    "contact.help.6.desc": "Interviews and features",
    "contact.cta.title": "Ready to Get Started?",
    "contact.cta.desc": "Drop us a line and we'll get back to you as soon as possible.",

    // About Founder Page
    "about.title": "About the Founder",
    "about.subtitle": "The person behind LernexAI",
    "about.name": "Sourav Maurya",
    "about.role": "Founder & CEO, LernexAI",
    "about.desc": "19-year-old coder and AI enthusiast building tools that solve real problems. Currently pursuing BCA at IGNOU.",
    "about.story.title": "Why I Built LernexAI",
    "about.story.p1": "Everywhere I went, I saw the same problem — people struggling to learn new things. Ask AI, search Google, watch videos... it's exhausting just to learn one simple concept. The headache of finding the right resource, the confusion of conflicting information, the frustration of getting stuck.",
    "about.story.p2": "So I built my own tool. LernexAI is my solution to this chaos — a personalized AI tutor that adapts to you, not the other way around. No more endless searching, no more one-size-fits-all courses. Just focused, efficient learning.",
    "about.story.p3": "That's easy — right? But making it actually work for real students, with real problems, that's the challenge I love.",
    "about.more.title": "More About Me",
    "about.more.1.title": "Self-Taught Developer",
    "about.more.1.desc": "Started coding at 16, learned everything from online resources. Built my first project before joining college.",
    "about.more.2.title": "Problem Solver at Heart",
    "about.more.2.desc": "I don't just code — I solve real problems. Every product I build addresses a genuine pain point I've experienced or observed.",
    "about.more.3.title": "Big Dreams, Small Steps",
    "about.more.3.desc": "I want to build products that impact millions. Starting with LernexAI and PyEater, but this is just the beginning.",
    "about.more.4.title": "Balancing Act",
    "about.more.4.desc": "Managing BCA studies at IGNOU while running two startups. It's challenging but I love every bit of it.",
    "about.vision.title": "My Vision",
    "about.vision.desc": "I want my products to help people. That's it. Whether it's LernexAI making education accessible, or my other projects solving different problems — my goal is simple: build things that make life easier for others.",
    "about.skills.title": "Background & Skills",
    "about.skills.1.title": "Coder & Prototyping Expert",
    "about.skills.1.desc": "Master at rapid prototyping and turning ideas into functional products quickly.",
    "about.skills.2.title": "BCA Student",
    "about.skills.2.desc": "Currently pursuing Bachelor of Computer Applications at IGNOU (1st Year).",
    "about.skills.3.title": "Founder of PyEater",
    "about.skills.3.desc": "Also built PyEater.in — an AI-powered spreadsheet auditing tool that scans spreadsheets to find and fix wrong formulas that cause financial damage.",
    "about.stats.title": "Quick Facts",
    "about.stats.1": "Years Old",
    "about.stats.2": "Products Built",
    "about.stats.3": "Ideas to Explore",
    "about.contact.title": "Let's Connect",
    "about.contact.desc": "Want to collaborate, have feedback, or just want to say hi? Feel free to reach out!",
  },
  hi: {
    // Navbar
    "nav.login": "लॉग इन",
    "nav.start": "मुफ्त शुरू करें",
    // Coming Soon
    "comingSoon.title": "रजिस्ट्रेशन जल्द आ रहा है!",
    "comingSoon.subtitle": "हम आपको सबसे अच्छा सीखने का अनुभव देने के लिए कड़ी मेहनत कर रहे हैं। हम बहुत जल्द लॉन्च करेंगे!",
    "comingSoon.button": "ठीक है!",

    // Hero
    "hero.badge": "🚀 नया: हिंदी में AI से डाउट सॉल्विंग",
    "hero.h1a": "पढ़ाई, अब",
    "hero.h1b": "आपके हिसाब से।",
    "hero.sub": "एक जैसे कोर्स काम नहीं करते। LernexAI आपके लक्ष्य के हिसाब से एक खास curriculum बनाता है और 24/7 tutor की तरह आपके साथ रहता है।",
    "hero.cta": "अपना सफर शुरू करें — मुफ़्त",
    "hero.demo": "डेमो देखें",
    "hero.social": "आज ही अपनी AI-powered learning journey शुरू करें।",

    // Problem
    "problem.heading": "पारंपरिक पढ़ाई में क्या गड़बड़ है।",
    "problem.card1.title": "एक जैसा Roadmap",
    "problem.card1.desc": "ज़्यादातर कोर्स \"सबके लिए एक\" रास्ता अपनाते हैं। अगर आप कहीं अटक गए तो कोई मदद नहीं।",
    "problem.card2.title": "सिर्फ़ वीडियो देखना",
    "problem.card2.desc": "बिना practice के वीडियो देखने से \"competence का भ्रम\" होता है। लगता है समझ गए, जब तक खुद बनाने न बैठें।",
    "problem.card3.title": "LernexAI का तरीका",
    "problem.card3.desc": "हम सिर्फ content नहीं देते। हम एक personalized ecosystem बनाते हैं जो आपके साथ grow करता है। कोई gap नहीं, कोई confusion नहीं।",
    "problem.badge1": "Dynamic Pace Adjustment",
    "problem.badge2": "Instant Feedback Loops",

    // Features
    "features.heading": "स्पष्टता के लिए बना।",
    "features.sub": "ऐसे टूल्स जो आपको असली चीज़ पर focus करने में मदद करें — सच में सीखना।",
    "features.f1.title": "AI Course Architect",
    "features.f1.desc": "बताएं आपका लक्ष्य — Web Dev हो या Stock Market — हमारा AI दुनिया के बेहतरीन resources से आपके level के हिसाब से रास्ता तैयार करेगा।",
    "features.f2.title": "Bilingual Tutor",
    "features.f2.desc": "कोई concept समझ नहीं आया? English या Hindi में हमारे AI से बात करें और आसान भाषा में समझें।",
    "features.f3.title": "Micro-Quizzes",
    "features.f3.desc": "हर module के बाद quiz दें। अगर गलत हुए तो AI तुरंत अलग तरीके से समझाएगा।",
    "features.f4.title": "Industry Recognized",
    "features.f4.desc": "AI-generated final projects पूरे करें और एक certificate पाएं जो employers को आपकी practical skills साबित करे।",

    // HowItWorks
    "how.heading": "तीन कदम, पहला नया skill।",
    "how.s1.title": "अपना लक्ष्य बताएं",
    "how.s1.desc": "बस बताएं क्या सीखना है और आपका current level क्या है। जैसे, 'मुझे basic HTML आती है, portfolio बनाना है।'",
    "how.s2.title": "Roadmap देखें",
    "how.s2.desc": "AI आपके लिए videos, articles और projects का sequence बनाएगा। चाहें तो बदलें, या सीधे शुरू हो जाएं।",
    "how.s3.title": "Guidance के साथ सीखें",
    "how.s3.desc": "पढ़ाई शुरू करें। हमारा AI Tutor हमेशा sidebar में रहेगा — concepts समझाने, code check करने या quiz लेने के लिए।",

    // CTA
    "cta.heading": "नया skill सीखने के लिए तैयार हैं?",
    "cta.sub": "उन छात्रों से जुड़ें जो AI-powered personalization से 2x तेज़ सीख रहे हैं। पढ़ाई का सबसे स्मार्ट तरीका अब यहाँ है।",
    "cta.btn": "मुफ़्त शुरू करें",

    // Footer
    "footer.privacy": "गोपनीयता",
    "footer.terms": "नियम",
    "footer.contact": "संपर्क",
    "footer.aboutFounder": "संस्थापक के बारे में",
    "footer.copy": "सर्वाधिकार सुरक्षित।",

    // Stats
    "stats.v1": "10K+",  "stats.l1": "सक्रिय छात्र",
    "stats.v2": "200+",  "stats.l2": "चुने हुए कोर्स",
    "stats.v3": "4.9★",  "stats.l3": "औसत रेटिंग",
    "stats.v4": "94%",   "stats.l4": "Completion Rate",

    // Subjects
    "subj.eyebrow": "क्या सीख सकते हैं",
    "subj.heading": "कोई भी subject। कोई भी level।",
    "subj.sub": "Competitive exams से लेकर cutting-edge tech तक — LernexAI हर लक्ष्य के लिए रास्ता बनाता है।",
    "subj.web": "Web Development", "subj.web.d": "HTML, CSS, React, Node.js और आगे।",
    "subj.stock": "Stock Market",  "subj.stock.d": "Fundamentals, technicals और options trading।",
    "subj.design": "UI/UX Design", "subj.design.d": "Figma, design systems और product thinking।",
    "subj.data": "Data Science",   "subj.data.d": "Python, SQL, pandas, ML pipelines।",
    "subj.ai": "AI & ML",          "subj.ai.d": "Deep learning, LLMs और model deployment।",
    "subj.exam": "Exam Prep",      "subj.exam.d": "JEE, NEET, UPSC, CAT और बहुत कुछ।",
    "subj.finance": "Personal Finance","subj.finance.d": "Budgeting, investing और financial planning।",
    "subj.cyber": "Cybersecurity", "subj.cyber.d": "Ethical hacking, networking और security।",

    // Testimonials
    "test.eyebrow": "छात्रों की बातें",
    "test.heading": "असली छात्र, असली नतीजे।",
    "test.featured": "मुझे coding का कोई knowledge नहीं था, 3 महीने में पहला freelance project मिल गया। AI tutor की Hindi explanations ने सब बदल दिया — अब Google पर basic cheezein नहीं ढूंढनी पड़तीं।",
    "test.featured.name": "विक्रम शर्मा", "test.featured.role": "Freelance Developer, जयपुर",
    "test.n1": "अर्जुन मेहता",  "test.r1": "B.Tech छात्र, दिल्ली",        "test.q1": "AI इतना adapt करता है। Recursion में अटका तो 3 अलग तरीकों से समझाया जब तक समझ नहीं आया। कोई YouTube video ऐसा नहीं करती।",
    "test.n2": "प्रिया नायर",   "test.r2": "MBA Aspirant, कोच्चि",         "test.q2": "Job के साथ CAT prep कर रही थी। LernexAI ने 2 घंटे का daily plan बनाया जो सच में काम आया। 98 percentile आया।",
    "test.n3": "राहुल गुप्ता",  "test.r3": "Stock Trader, पुणे",           "test.q3": "पहले सिर्फ YouTube देख कर confuse हो जाता था। LernexAI ने quizzes के साथ proper roadmap दिया — अब confidently trade करता हूँ।",
    "test.n4": "स्नेहा रेड्डी", "test.r4": "UX Designer, हैदराबाद",        "test.q4": "Project assignments सबसे अच्छे थे। Real briefs, AI से real feedback। Portfolio 0 से 6 case studies हो गया।",
    "test.n5": "करण वर्मा",    "test.r5": "Data Analyst, बंगलोर",         "test.q5": "3 हफ्तों में SQL interview clear हो गया। Micro-quizzes ने honest रखा — hard parts skip नहीं हो सके।",
    "test.n6": "मीरा अय्यर",   "test.r6": "Class 12 की छात्रा, चेन्नई",  "test.q6": "JEE prep impossible लगती थी जब तक LernexAI ने छोटे daily goals में नहीं तोड़ा। Mock tests में panic आना बंद हो गया।",

    // Pricing
    "price.eyebrow": "Pricing",
    "price.heading": "सीधी, ईमानदार कीमत।",
    "price.sub": "मुफ़्त शुरू करें। जब तैयार हों, Pro लें।",
    "price.month": "महीना",
    "price.popular": "सबसे लोकप्रिय",
    "price.note": "शुरुआत के लिए credit card नहीं चाहिए। Pro कभी भी cancel करें।",
    "price.free.label": "Free",
    "price.free.desc": "AI-guided learning explore करने के लिए एकदम सही।",
    "price.free.f1": "3 AI-generated learning roadmaps",
    "price.free.f2": "Basic bilingual tutor (EN + HI)",
    "price.free.f3": "10 micro-quizzes प्रति माह",
    "price.free.f4": "Community forum access",
    "price.free.cta": "मुफ़्त शुरू करें",
    "price.pro.label": "Pro",
    "price.pro.desc": "beginner से job-ready तक जाने के लिए सब कुछ, तेज़ी से।",
    "price.pro.f1": "Unlimited AI roadmaps और course curation",
    "price.pro.f2": "24/7 bilingual AI tutor (EN + HI)",
    "price.pro.f3": "Unlimited micro-quizzes और assessments",
    "price.pro.f4": "AI-generated final projects",
    "price.pro.f5": "Industry-recognized certificate",
    "price.pro.f6": "Priority support",
    "price.pro.cta": "Pro शुरू करें — ₹499/माह",

    // Certificate
    "cert.eyebrow": "Certification",
    "cert.heading": "Certificate पाएं। Skills साबित करें।",
    "cert.sub": "AI-curated course पूरा करें, final test दें, और सिर्फ ₹99 में graded certificate पाएं। जितना अच्छा सीखा, उतना अच्छा grade।",
    "cert.s1.title": "AI Course पूरा करें",
    "cert.s1.desc": "अपना personalized learning path — videos, projects और quizzes — पूरा करें जब तक तैयार न हो जाएं।",
    "cert.s2.title": "Final Test दें",
    "cert.s2.desc": "LernexAI आपके course के हिसाब से exam तैयार करता है। Score के आधार पर आपका grade तय होगा।",
    "cert.s3.title": "Graded Certificate पाएं",
    "cert.s3.desc": "₹99 pay करें, grade के साथ certificate download करें, और LinkedIn या employers के साथ share करें।",
    "cert.price.label": "एक बार की certificate fee",
    "cert.price.note": "सिर्फ course और test complete करने के बाद",
    "cert.price.cta": "और जानें",
    "cert.grade.title": "Grade Scale — आपका Score, आपका Grade",
    "cert.grade.note": "Final test score के आधार पर grade मिलता है। Retake बिल्कुल free।",

    // FAQ
    "faq.eyebrow": "FAQ",
    "faq.heading": "सवाल हैं?",
    "faq.q1": "क्या शुरू करने के लिए कोई prior knowledge चाहिए?",
    "faq.a1": "बिल्कुल नहीं। LernexAI roadmap बनाने से पहले आपका current level पूछता है। चाहे आप complete beginner हों या level up करना चाहते हों, AI सब कुछ उसी हिसाब से बनाता है।",
    "faq.q2": "यह Udemy या YouTube से कैसे अलग है?",
    "faq.a2": "Udemy एक fixed course देता है। YouTube chaos देता है। LernexAI web के best resources से एक custom, adaptive path बनाता है — और एक live tutor की तरह आपके साथ रहता है, pre-recorded video की तरह नहीं।",
    "faq.q3": "क्या मैं Hindi में सीख सकता/सकती हूँ?",
    "faq.a3": "हाँ! हमारा AI tutor कोई भी concept Hindi में समझा सकता है। Navbar में EN|HI toggle से पूरा interface Hindi में switch करें।",
    "faq.q4": "Certificate कैसे काम करता है?",
    "faq.a4": "AI-generated final project complete करने के बाद system आपका submission evaluate करता है और mastery का certificate issue करता है। इसमें project, score, और LinkedIn पर share करने योग्य verifiable link होता है।",
    "faq.q5": "क्या Pro plan exam prep (JEE/NEET/UPSC) के लिए worth it है?",
    "faq.a5": "बिल्कुल। Pro में unlimited practice tests, detailed performance analytics, और एक AI tutor मिलता है जो बताता है कि गलती क्यों हुई — सिर्फ सही जवाब नहीं देता। Pro students mock tests में consistently बेहतर perform करते हैं।",
    "faq.q6": "क्या Pro subscription कभी भी cancel हो सकती है?",
    "faq.a6": "हाँ, कोई सवाल नहीं। Account settings से cancel करें और billing period के अंत तक Pro access रहेगा।",

    // Privacy Page
    "privacy.title": "गोपनीयता नीति",
    "privacy.subtitle": "आपकी डेटा सुरक्षा हमारी प्राथमिकता है",
    "privacy.hero.title": "हम आपकी गोपनीयता को गंभीरता से लेते हैं",
    "privacy.hero.desc": "LernexAI में, हम पारदर्शिता में विश्वास करते हैं। यह नीति बताती है कि हम आपकी व्यक्तिगत जानकारी कैसे एकत्र करते हैं, उपयोग करते हैं और सुरक्षित रखते हैं। आपका विश्वास हमारे लिए मायने रखता है।",
    "privacy.collect.title": "हम क्या जानकारी एकत्र करते हैं",
    "privacy.collect.desc": "हम जानकारी एकत्र करते हैं जो आप हमें सीधे तौर पर प्रदान करते हैं जब आप हमारी सेवाओं का उपयोग करते हैं:",
    "privacy.collect.1": "नाम और ईमेल पता",
    "privacy.collect.2": "शिक्षा वरीयताएं और लक्ष्य",
    "privacy.collect.3": "उपयोग डेटा और सीखने की प्रगति",
    "privacy.collect.4": "भुगतान जानकारी (सुरक्षित रूप से संसाधित)",
    "privacy.use.title": "हम आपकी जानकारी का उपयोग कैसे करते हैं",
    "privacy.use.1.title": "आपकी शिक्षा को व्यक्तिगत बनाएं",
    "privacy.use.1.desc": "आपके लक्ष्यों और प्रगति के आधार पर पाठ्यक्रम अनुकूलित करें",
    "privacy.use.2.title": "भुगतान संसाधित करें",
    "privacy.use.2.desc": "सदस्यताओं को सुरक्षित और कुशलता से संभालें",
    "privacy.use.3.title": "अपडेट भेजें",
    "privacy.use.3.desc": "शैक्षिक सामग्री और प्लेटफ़ॉर्म अपडेट प्रदान करें",
    "privacy.use.4.title": "हमारे AI को बेहतर बनाएं",
    "privacy.use.4.desc": "सीखने के एल्गोरिदम को बढ़ाने के लिए उपयोग पैटर्न का विश्लेषण करें",
    "privacy.security.title": "डेटा सुरक्षा",
    "privacy.security.desc": "हम आपकी व्यक्तिगत डेटा की रक्षा के लिए उद्योग-मानक सुरक्षा उपाय लागू करते हैं:",
    "privacy.security.1": "डेटा के लिए 256-बिट एन्क्रिप्शन",
    "privacy.security.2": "नियमित सुरक्षा ऑडिट और प्रवेश परीक्षण",
    "privacy.security.3": "कड़ी पहुंच नियंत्रण और प्रमाणीकरण",
    "privacy.security.4": "डेटा सुरक्षा विनियमों का अनुपालन",
    "privacy.contact.title": "आपकी गोपनीयता के बारे में प्रश्न?",
    "privacy.contact.desc": "हम मदद के लिए यहां हैं। किसी भी समय हमसे संपर्क करें।",

    // Terms Page
    "terms.title": "सेवा की शर्तें",
    "terms.subtitle": "LernexAI का उपयोग करने के लिए नियम और दिशानिर्देश",
    "terms.hero.title": "शर्तों पर सहमति",
    "terms.hero.desc": "LernexAI का उपयोग करके, आप इन शर्तों से सहमत होते हैं। कृपया अपने अधिकारों और दायित्वों को समझने के लिए उन्हें ध्यान से पढ़ें।",
    "terms.accept.title": "शर्तों की स्वीकृति",
    "terms.accept.desc": "LernexAI सेवाओं तक पहुंच या उनका उपयोग करके, आप इन सेवा की शर्तों से बंधे होने के लिए सहमत होते हैं। यदि आप इन शर्तों से सहमत नहीं हैं, तो कृपया हमारी सेवाओं का उपयोग न करें। ये शर्तें आप और LernexAI के बीच एक कानूनी रूप से बाध्यकारी समझौता बनाती हैं।",
    "terms.responsibilities.title": "उपयोगकर्ता दायित्व",
    "terms.responsibilities.1": "खाता गोपनीयता बनाए रखें",
    "terms.responsibilities.2": "सटीक जानकारी प्रदान करें",
    "terms.responsibilities.3": "केवल शैक्षिक उद्देश्यों के लिए उपयोग करें",
    "terms.responsibilities.4": "खाता क्रेडेंशियल्स साझा न करें",
    "terms.responsibilities.5": "लागू कानूनों का पालन करें",
    "terms.responsibilities.6": "समस्याओं को तुरंत रिपोर्ट करें",
    "terms.payment.title": "सदस्यता और भुगतान",
    "terms.payment.1.title": "मुफ्त और भुगतान योजनाएं",
    "terms.payment.1.desc": "हम विभिन्न जरूरतों के लिए मुफ्त और भुगतान सदस्यता योजनाएं प्रदान करते हैं",
    "terms.payment.2.title": "पुनरावर्ती बिलिंग",
    "terms.payment.2.desc": "भुगतान सदस्यताएं एक पुनरावर्ती आधार पर बिल की जाती हैं (मासिक)",
    "terms.payment.3.title": "रद्दीकरण नीति",
    "terms.payment.3.desc": "खाता सेटिंग्स से किसी भी समय रद्द करें। बिलिंग अवधि के अंत तक पहुंच",
    "terms.payment.4.title": "कोई रिफंड नहीं",
    "terms.payment.4.desc": "सभी शुल्क गैर-वापसी हैं जब तक कानून द्वारा आवश्यक न हो",
    "terms.ip.title": "बौद्धिक संपदा",
    "terms.ip.desc": "LernexAI की सभी सामग्री, सुविधाएं और कार्यक्षमता LernexAI के स्वामित्व में हैं और अंतरराष्ट्रीय कॉपीराइट, ट्रेडमार्क और अन्य बौद्धिक संपदा कानूनों द्वारा संरक्षित हैं।",
    "terms.ip.note": "उपयोगकर्ता स्पष्ट अनुमति के बिना पुनरुत्पादन, वितरण या डेरिवेटिव कार्य नहीं कर सकते।",
    "terms.liability.title": "दायित्व की सीमा",
    "terms.liability.desc": "LernexAI किसी भी अप्रत्यक्ष, आकस्मिक, विशेष या परिणामी क्षति के लिए उत्तरदायी नहीं होगा जो हमारी सेवाओं के उपयोग या उपयोग करने में असमर्थ से उत्पन्न होती है। हमारी दायित्व लागू कानून द्वारा अनुमत अधिकतम सीमा तक सीमित है।",
    "terms.contact.title": "इन शर्तों के बारे में प्रश्न?",
    "terms.contact.desc": "हम किसी भी संदेह को स्पष्ट करने में खुश हैं।",

    // Contact Page
    "contact.title": "संपर्क करें",
    "contact.subtitle": "हमें सुनना अच्छा लगेगा",
    "contact.hero.title": "संपर्क में रहें",
    "contact.hero.desc": "कोई प्रश्न, प्रतिक्रिया, या सहयोग करना चाहते हैं? हम मदद के लिए यहां हैं और आपसे सुनना पसंद करेंगे।",
    "contact.email.title": "हमें ईमेल करें",
    "contact.email.desc": "किसी भी पूछताछ, सहायता, या प्रतिक्रिया के लिए, कृपया ईमेल के माध्यम से हमसे संपर्क करें:",
    "contact.response.title": "प्रतिक्रिया समय",
    "contact.response.desc": "हम आमतौर पर सभी ईमेल का 24-48 घंटे के भीतर उत्तर देते हैं।",
    "contact.response.note": "तत्काल मामलों के लिए, कृपया अपने विषय लाइन में \"URGENT\" शामिल करें।",
    "contact.help.title": "हम क्या मदद कर सकते हैं",
    "contact.help.1.title": "सामान्य पूछताछ",
    "contact.help.1.desc": "LernexAI सेवाओं के बारे में प्रश्न",
    "contact.help.2.title": "तकनीकी सहायता",
    "contact.help.2.desc": "समस्या निवारण और सहायता",
    "contact.help.3.title": "बिलिंग प्रश्न",
    "contact.help.3.desc": "सदस्यताएं और भुगतान",
    "contact.help.4.title": "साझेदारी",
    "contact.help.4.desc": "सहयोग के अवसर",
    "contact.help.5.title": "प्रतिक्रिया",
    "contact.help.5.desc": "सुझाव और सुधार",
    "contact.help.6.title": "प्रेस और मीडिया",
    "contact.help.6.desc": "साक्षात्कार और फीचर",
    "contact.cta.title": "शुरू करने के लिए तैयार?",
    "contact.cta.desc": "हमें एक लाइन ड्रॉप करें और हम जल्द से जल्द आपको वापस करेंगे।",

    // About Founder Page
    "about.title": "संस्थापक के बारे में",
    "about.subtitle": "LernexAI के पीछे व्यक्ति",
    "about.name": "सौरव मौर्य",
    "about.role": "संस्थापक और सीईओ, LernexAI",
    "about.desc": "19 वर्षीय कोडर और AI उत्साही जो वास्तविक समस्याओं को हल करने वाले टूल बना रहा है। वर्तमान में IGNOU में BCA कर रहा है।",
    "about.story.title": "मैंने LernexAI क्यों बनाया",
    "about.story.p1": "जहां भी मैं गया, मैंने वही समस्या देखी — लोग नई चीजें सीखने में संघर्ष कर रहे थे। AI से पूछो, Google पर खोजो, वीडियो देखो... एक साधारण अवधारि सीखने के लिए यह थकाऊ है। सही संसाधन ढूंढने का सिरदर्द, विरोधी जानकारी का भ्रम, फंसने की निराशा।",
    "about.story.p2": "तो मैंने अपना खुद का टूल बनाया। LernexAI इस अराजक का मेरा समाधान है — एक व्यक्तिगत AI ट्यूटर जो आपके अनुसार अनुकूल होता है, इसके विपरीत नहीं। कोई अंतहीन खोज नहीं, कोई एक-आकार-सभी-फिट कोर्स नहीं। सिर्फ केंद्रित, कुशल सीखना।",
    "about.story.p3": "यह आसान है — है ना? लेकिन वास्तविक छात्रों के लिए, वास्तविक समस्याओं के साथ इसे वास्तव में काम करना, वह चुनौती है जिसे मैं प्यार करता हूं।",
    "about.more.title": "मेरे बारे में और",
    "about.more.1.title": "स्व-सिखाया डेवलपर",
    "about.more.1.desc": "16 साल की उम्र में कोडिंग शुरू की, ऑनलाइन संसाधनों से सब कुछ सीखा। कॉलेज ज्वाइन करने से पहले अपना पहला प्रोजेक्ट बनाया।",
    "about.more.2.title": "दिल से समस्या समाधानक",
    "about.more.2.desc": "मैं सिर्फ कोड नहीं करता — मैं वास्तविक समस्याओं को हल करता हूं। मैं जो हर उत्पाद बनाता हूं वह एक वास्तविक पीड़ा बिंदु को संबोधता है जिसे मैंने अनुभव किया है या देखा है।",
    "about.more.3.title": "बड़े सपने, छोटे कदम",
    "about.more.3.desc": "मैं उत्पाद बनाना चाहता हूं जो लाखों लोगों को प्रभावित करें। LernexAI और PyEater से शुरू करके, लेकिन यह सिर्फ शुरुआत है।",
    "about.more.4.title": "संतुलन का खेल",
    "about.more.4.desc": "IGNNOU में BCA पढ़ाई का प्रबंधन करते हुए दो स्टार्टअप चलाना। यह चुनौतीपूर्ण है लेकिन मैं इसके हर पल से प्यार करता हूं।",
    "about.vision.title": "मेरा दृष्टिकोण",
    "about.vision.desc": "मैं चाहता हूं कि मेरे उत्पाद लोगों की मदद करें। बस इतना ही। चाहे LernexAI शिक्षा को सुलभ बना रहा हो, या मेरे अन्य प्रोजेक्ट अलग समस्याओं को हल कर रहे हों — मेरा लक्ष्य सरल है: चीजें बनाएं जो लोगों की जिंदगी आसान बनाएं।",
    "about.skills.title": "पृष्ठभूमि और कौशल",
    "about.skills.1.title": "कोडर और प्रोटोटाइपिंग विशेषज्ञ",
    "about.skills.1.desc": "तेजी से प्रोटोटाइपिंग और विचारों को कार्यात्मक उत्पादों में बदलने में माहिर।",
    "about.skills.2.title": "BCA छात्र",
    "about.skills.2.desc": "वर्तमान में IGNOU में कंप्यूटर एप्लीकेशन की स्नातक की डिग्री कर रहा है (1st Year)।",
    "about.skills.3.title": "PyEater के संस्थापक",
    "about.skills.3.desc": "PyEater.in भी बनाया — एक AI-संचालित स्प्रेडशीट ऑडिटिंग टूल जो स्प्रेडशीट स्कैन करता है और गलत फॉर्मूला खोजता और ठीक करता है जो वित्तीय नुकसान का कारण बनता है।",
    "about.stats.title": "त्वरित तथ्य",
    "about.stats.1": "साल की उम्र",
    "about.stats.2": "उत्पाद बनाए",
    "about.stats.3": "विचार एक्सप्लोर करने के लिए",
    "about.contact.title": "आइए जुड़ें",
    "about.contact.desc": "सहयोग करना चाहते हैं, प्रतिक्रिया है, या बस हाय कहना चाहते हैं? बेझिझक संपर्क करें!",
  },
};

export const LanguageContext = createContext<LanguageContextType | null>(null);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLang] = useState<Lang>("en");

  const t = (key: string): string => {
    return translations[lang][key] ?? translations["en"][key] ?? key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

